### ISSUE TITLE
Panic when an upstream PR body is missing the ending block of `upstream-prs`

### ISSUE THREAD

**Issue by christarazi** [cilium/release#4]
Stack trace:

```
Generating CHANGELOG.md
Comparing 1.6.9...f71a95703f17637d6837067ffe604b9795221296
Comparing 1.6.9...5692afde1d0b958f346f0b14530865c3a2a654f3
Comparing 1.6.9...5692afde1d0b958f346f0b14530865c3a2a654f3
Found 34 commits!
....................................panic: runtime error: slice bounds out of range [:-1]goroutine 1 [running]:
github.com/cilium/release/pkg/github.textBlockBetween(0xc000114900, 0x416, 0x72fd90, 0xf, 0x39d, 0x0)
        /home/chris/code/cilium/release/pkg/github/labels.go:45 +0x29a
github.com/cilium/release/pkg/github.getUpstreamPRs(0xc000114900, 0x416, 0x3035, 0x9b52c0, 0x0)
        /home/chris/code/cilium/release/pkg/github/labels.go:52 +0xa1
github.com/cilium/release/pkg/github.GeneratePatchRelease(0x79e140, 0xc000028300, 0xc000126280, 0x7460b0, 0xc00006ed20, 0xc00006ed50, 0xc000142000, 0x22, 0x40, 0x0, ...)
        /home/chris/code/cilium/release/pkg/github/release.go:78 +0x1e0
main.main()
        /home/chris/code/cilium/release/cmd/main.go:171 +0x664
```

This occurs because this function never updates the value of `end` (stays at `-1`). The value is never modified because it is possible to have an upstream PR that has a missing ending block of its `upstream-prs` block.

For example:
![image](https://user-images.githubusercontent.com/3885308/86303545-ef3ba580-bbc0-11ea-98ab-c9aa17682fe4.png)

I worked around this by...well editing the PR body to have the ending block :)

**Comment by aanm** [comment]
it is required to have the `upstream-prs` wrapped by ``` so it's preferable to panic than trying to work around it.
